In [2]:
from numpy import *

In [4]:
arr1 = arange(6).reshape(2,3)
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [5]:
arr2 = arange(6,12).reshape(3,2)
arr2

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [7]:
# Performinig Dot Product Oerstion

arr1.dot(arr2)

array([[ 28,  31],
       [100, 112]])