In [1]:
#finding a Min and Max Vale


In [2]:
from numpy import *


In [4]:
arr1 = arange(10).reshape(2,5)
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
arr2 = arange(10,20).reshape(2,5)
arr2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
arr1.min()
arr2.min()

10

In [9]:
arr1.min()

0

In [10]:
arr1.max()

9

In [11]:
arr2.max()

19

In [13]:
#finding a max and min row coll form the matrix

In [14]:
# for finding min row and coll
arr1.min(axis = 0)

array([0, 1, 2, 3, 4])

In [17]:
arr1.min(axis = 1)

array([0, 5])

In [18]:
# for finding max row and coll
arr2.max(axis=0)

array([15, 16, 17, 18, 19])

In [19]:
arr2.max(axis=1)

array([14, 19])

In [20]:
arr2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])