In [1]:
# sum min median mod sum operation perform

In [2]:
from numpy import *

In [3]:
arr1 = arange(10).reshape(2,5)
arr2 = arange(10,20).reshape(5,2)

In [4]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
arr2

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [6]:
arrarr1.sum()

NameError: name 'arrarr1' is not defined

In [ ]:
# row and coll wise sum 
# 0 = coll
# 1 = row 
arr1.sum(axis=0)

array([ 5,  7,  9, 11, 13])

In [ ]:
arr1.sum(axis=1)

array([10, 35])

In [ ]:
arr2.sum()

145

In [ ]:
arr2.sum(axis=0)

array([70, 75])

In [ ]:
arr2.sum(axis=1)

array([21, 25, 29, 33, 37])

In [ ]:
# finding mean
arr1.mean()

4.5

In [ ]:
# row coll wise mean
arr2.mean(axis=0)

array([14., 15.])

In [ ]:
# findin std for hole matrix and also row and coll wise
arr2.mean(axis=1)

array([10.5, 12.5, 14.5, 16.5, 18.5])

In [ ]:
arr1.std()

2.8722813232690143

In [ ]:
arr1.std(axis=0)

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [ ]:
arr2.std(axis=0)

array([2.82842712, 2.82842712])

In [ ]:
# finding the median
median(arr1)

4.5

In [ ]:
median(arr2)

14.5