In [2]:
from numpy import *

In [3]:
arr1 = arange(10).reshape(2,5)
arr2 = arange(10,20).reshape(5,2)

In [4]:
sin(arr1)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [5]:
cos(arr2)

array([[-0.83907153,  0.0044257 ],
       [ 0.84385396,  0.90744678],
       [ 0.13673722, -0.75968791],
       [-0.95765948, -0.27516334],
       [ 0.66031671,  0.98870462]])

In [6]:
tan(arr1)

array([[ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128],
       [-3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566]])

In [7]:
tan(arr2)

array([[ 6.48360827e-01, -2.25950846e+02],
       [-6.35859929e-01,  4.63021133e-01],
       [ 7.24460662e+00, -8.55993401e-01],
       [ 3.00632242e-01,  3.49391565e+00],
       [-1.13731371e+00,  1.51589471e-01]])

In [8]:
cos(arr2)

array([[-0.83907153,  0.0044257 ],
       [ 0.84385396,  0.90744678],
       [ 0.13673722, -0.75968791],
       [-0.95765948, -0.27516334],
       [ 0.66031671,  0.98870462]])